
name: build and deploy on main branch

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Exit if not on main branch
      if: endsWith(github.ref, 'main') == false
      run: exit -1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./src/patternsSite/package-lock.json"
    - run: |
        cd src
        cd patternsSite
        npm i
    - run: |
        cd src        
        cd patternsSite
        npm run build --if-present
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: patternsSite-build
        path: src/patternsSite/build/

    - name: upload documentation to github pages
      run: |
        cp -r v2/patternsSite/build/* docs/v2/
        git config --global user.email "ignatandrei@yahoo.com"
        git config --global user.name "Andrei Ignat Automation"
        git add docs/v2
        git commit -m "Deploy documentation"
        git push origin HEAD:main  
